Draft: Update to generate datum conversion grid
ClimateImpactLab/sliiders-archived pull request #19
Opened 2022-03-31 16:39 UTC by jtschoi

TODO:
- [ ] Make sure that the raw dataset downloads are replicable (currently, instructions cause cropping of the entire grid)

2022-03-31 21:17 UTC, bolliger32 commented
This looks great! Let's hold off on merging until #15 is merged and we rebase this branch. A couple of the notebooks currently in `exposure` have been renamed in that PR to remove spaces in the filenames and to renumber them a bit b/c some of them have been consolidated. So lets just get that one merged first and then get this branch rebased onto the new main branch HEAD

2022-04-05 17:24 UTC, jtschoi commented
@bolliger32 @dpa9694 merge conflict with the latest PR (#15) has been resolved, and I think it is good to go. Also, changed the numberings in `notebooks/create-SLIIDERS-ECON/exposure` due to adding `6-generate_datum_conversion_grid.ipynb`. Could you make sure whether this is the suitable place to have this file, so that the procedure in ``notebooks/create-SLIIDERS-ECON/exposure` runs smoothly?

2022-04-05 17:55 UTC, bolliger32 requested changes
some simple changes in the py files and then a few in the notebooks coming via ReviewNB

2022-04-05 17:55 UTC, bolliger32 commented on sliiders/country_level_ypk.py
> +from pathlib import Path
I don't think this import is needed, correct?

2022-04-05 17:55 UTC, bolliger32 commented on sliiders/spatial.py
> +from pyinterp.backends.xarray import Grid2D
Same here - this import isn't used is it?

2022-04-05 17:55 UTC, bolliger32 commented on notebooks/create-SLIIDERS-ECON/download-sliiders-econ-input-data.ipynb
>      "MPD_DIRECTORY = Path(os.path.dirname(sset.PATH_MPD_RAW))\n",
<pre class="ql-syntax" spellcheck="false">Line #2.    PWT_DIRECTORY = Path(os.path.dirname(sset.PATH_PWT_RAW))
</pre><p>Let's use just e.g. <code>set.PATH_PWT_RAW.parent</code> for these, rather than mixing os.path and path lib.Path</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ClimateImpactLab/sliiders/pull/19/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2022-04-05 17:55 UTC, bolliger32 commented on notebooks/create-SLIIDERS-ECON/download-sliiders-econ-input-data.ipynb
>      "MPD_DIRECTORY = Path(os.path.dirname(sset.PATH_MPD_RAW))\n",
<pre class="ql-syntax" spellcheck="false">Line #32.        os.makedirs(direc, exist_ok=True)
</pre><p>This can be <code>direc.mkdir(exist_ok=True, parents=True)</code>(again to stick with pathlib.Path.</p><p> </p><p>In the future, we can probably avoid using GCSFUSE altogether and just place these as objects on GCS, using fsspec/gcsfs to access them and not needed to create directories. But that's a longer change and not really important.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ClimateImpactLab/sliiders/pull/19/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2022-04-05 17:55 UTC, bolliger32 commented on notebooks/create-SLIIDERS-ECON/exposure/6-generate_datum_conversion_grid.ipynb
> +{
<p>This version history is relevant for glo-co but I don't think we need to include it here. Ultimately, it would be nice to set all these intermediate data file versions to v1.0 for this release. I don't think we need to do that pre-re-submission, but I'll add that to the list of to-dos post submission. For now, I think we can still remove these history descriptions since all of this history is pre-release.</p><p> </p><p>Can you also check for stuff like this in other notebooks? Maybe use code-server's "find in all files" functionality and search for HISTORY all caps?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ClimateImpactLab/sliiders/pull/19/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2022-04-05 17:55 UTC, bolliger32 commented on notebooks/create-SLIIDERS-ECON/exposure/6-generate_datum_conversion_grid.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    def interpolate_da_like(da_in, da_out):
</pre><p>move the first function to spatial.py and the second to io.py</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ClimateImpactLab/sliiders/pull/19/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2022-04-05 18:51 UTC, jtschoi commented on sliiders/spatial.py
> +from pyinterp.backends.xarray import Grid2D
`Grid2D` kept in place due to adding `interpolate_da_like` in `spatial.py`

2022-04-05 18:52 UTC, jtschoi commented on sliiders/country_level_ypk.py
> +from pathlib import Path
`pathlib.Path` import removed!

2022-04-05 18:53 UTC, jtschoi commented on notebooks/create-SLIIDERS-ECON/exposure/6-generate_datum_conversion_grid.ipynb
> +{
functions now moved to `spatial.py` and `io.py`

2022-04-05 18:57 UTC, jtschoi commented on notebooks/create-SLIIDERS-ECON/exposure/6-generate_datum_conversion_grid.ipynb
> +{
Version history removed here, and I will check for others as well!

2022-04-05 19:05 UTC, jtschoi commented on notebooks/create-SLIIDERS-ECON/download-sliiders-econ-input-data.ipynb
>      "MPD_DIRECTORY = Path(os.path.dirname(sset.PATH_MPD_RAW))\n",
Changed the `os.makedirs` line to use `.mkdir` instead

2022-04-05 19:06 UTC, jtschoi commented on notebooks/create-SLIIDERS-ECON/download-sliiders-econ-input-data.ipynb
>      "MPD_DIRECTORY = Path(os.path.dirname(sset.PATH_MPD_RAW))\n",
Changed all cases to use `.parent` instead

2022-04-05 19:30 UTC, bolliger32 approved these changes
Thanks for the changes. Looks good!

2022-04-05 19:30 UTC, merged